#!/bin/bash

set -ue -o pipefail

input=${1:-"/dev/stdin"}

# Avoid sorting header
n=1
while read line; do
    if [[ ! "$line" =~ ^\# ]]; then
        echo "Expected header line. Assuming no header.\n Line $line" > /dev/stderr
        if [[ $input == /dev/stdin ]]; then
            # Put line back into stdin
            echo $line > $input
        fi
        break
    fi
    echo "$line"
    n=$((n+1))

    if [[ "$line" =~ ^\#CHROM ]]; then
        break
    fi
done < $input

# Sort data part of vcf
if [[ $input == /dev/stdin ]]; then
    # If stdin, the header lines have already been read
    cat $input | sort -k1,1V -k2,2n -k4,5
else
    # If file, we need to skip the header lines, and sort the rest
    tail --lines +$n $input | sort -k1,1V -k2,2n -k4,5
fi


